### ISSUE TITLE
add `py.typed` to 0.24.0?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/starlette-feedstock#81]
### Comment:

Thanks for maintaining this!

`fastapi` pins with `==` to `0.24.0`, but that [`sdist`](https://pypi.org/project/starlette/0.20.4/#files) doesn't include `py.typed` which bothers tools that follow the PEP561 strictly (e.g. `mypy`).

Would it be possible to get a historical build of that version with this before `pip install`:

```yaml
outputs:
  - name: {{ name }}
    build:
      script: 
        - python -c "__import__('pathlib').Path('starlette/py.typed').touch()"
        - python -m pip install . --no-deps --no-build-isolation -vv
```
